/**
 * Page that displays the GitHub profile metrics SVG generated by lowlighter/metrics.
 * The SVG is built into the app at public/github-metrics.svg and deployed with the site.
 */
function GitHubStatsPage() {
	const metricsSrc = `${import.meta.env.BASE_URL}github-metrics.svg`

	return (
		<div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12 pt-4">
			<header className="text-center mb-8 sm:mb-12">
				<div className="inline-block mb-4">
					<span className="text-theme-accent font-semibold text-sm uppercase tracking-wider">
						Profile
					</span>
				</div>
				<h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-theme-text-primary mb-4">
					GitHub stats
				</h1>
				<p className="text-lg text-theme-text-secondary max-w-2xl mx-auto">
					Contribution graph, languages, and activity metrics from my GitHub profile.
				</p>
			</header>

			<div className="rounded-xl border border-theme bg-theme-surface overflow-hidden">
				<img
					src={metricsSrc}
					alt="GitHub profile metrics: contributions, languages, and activity"
					className="w-full h-auto block"
					loading="lazy"
				/>
			</div>

			<p className="mt-6 text-center text-sm text-theme-text-muted">
				<a
					href="https://github.com/kmavillanosa"
					target="_blank"
					rel="noopener noreferrer"
					className="text-theme-accent hover:underline"
				>
					View profile on GitHub
				</a>
			</p>
		</div>
	)
}

export default GitHubStatsPage
